CV-project/Controllers/AdminController.cs
using CV_project.Models;
using CV_project.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CV_project.Controllers
{
    public class AdminController : Controller
    {
        private readonly ILogger<CompanyController> _logger;
        private readonly IAdminService _adminService;
        public AdminController(ILogger<CompanyController> logger, IAdminService adminService)
        {
            _logger = logger;
            _adminService = adminService;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet("/RegisterForCompany")]
        public IActionResult RegisterForCompany()
        {
            if (HttpContext.Session.GetString("Usersession") == null)
                return RedirectToAction("SignIn","Home");
            InfoViewModel infoSession = new InfoViewModel();
            infoSession = JsonConvert.DeserializeObject<InfoViewModel>(HttpContext.Session.GetString("Usersession"));
            if(infoSession.AccountType!=3)
                return RedirectToAction("SignIn", "Home");
            return View(new RegisterCompanyViewModel());
        }
        [HttpPost("/RegisterForCompany")]
        public async Task<IActionResult> RegisterForCompany(RegisterCompanyViewModel registerViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(registerViewModel);
            }
            var registerSucess = await _adminService.RegisterAsync(registerViewModel);

            if (!registerSucess)
            {
                return View(registerViewModel);
            }
            return RedirectToAction("SignIn", "Home");
        }
        public IActionResult ListCompany()
        {
            if (HttpContext.Session.GetString("Usersession") == null)
                return RedirectToAction("SignIn", "Home");
            return View();
        }
    }
}

CV-project/Controllers/CompanyController.cs
using CV_project.Data;
using CV_project.Data.Entities;
using CV_project.Models;
using CV_project.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CV_project.Controllers
{
    public class CompanyController : Controller
    {
        private readonly ILogger<CompanyController> _logger;
        private readonly ICompanyService _companyService;
        private readonly REOrganizationContext _context;
        public CompanyController(ILogger<CompanyController> logger, ICompanyService companyService, REOrganizationContext context)
        {
            _logger = logger;
            _companyService = companyService;
            _context = context;
        }
        public async Task<IActionResult> ViewCV(int pageNumber = 1)
        {
            if (HttpContext.Session.GetString("Usersession") == null)
                return RedirectToAction("SignIn");

            InfoViewModel infoSession = new InfoViewModel();
            infoSession = JsonConvert.DeserializeObject<InfoViewModel>(HttpContext.Session.GetString("Usersession"));
            var idCompany = await (from c in _context.Accounts
                                   join d in _context.Companies on c.AccountId equals d.AccountId
                                   where c.AccountId == infoSession.accountId
                                   select d.CompanyId
                                    ).FirstOrDefaultAsync();
            var listCV = new List<WebCv>();
            listCV = await (from c in _context.WebCvs
                                join d in _context.Applicants on c.Cvid equals d.Cvid
                                join e in _context.Applies on d.ApplicantId equals e.ApplicantId
                                where e.CompanyId == idCompany
                                select c).ToListAsync();
            var model = PagingList<WebCv>.CreateAsync(listCV, pageNumber, 1);
            return View(model);
        }
        [HttpGet("/CreateCompanyProfile")]
        public IActionResult CreateCompanyProfile()
        {
            return View();
        }
        [HttpPost("/CreateCompanyProfile")]
        public async Task<IActionResult> CreateCompanyProfile(CompanyProfile comProfile)
        {
            if (!ModelState.IsValid)
            {
                return View(comProfile);
            }
            if (HttpContext.Session.GetString("Usersession") == null)
                return RedirectToAction("SignIn");

            InfoViewModel infoSession = new InfoViewModel();
            infoSession = JsonConvert.DeserializeObject<InfoViewModel>(HttpContext.Session.GetString("Usersession"));
            await _companyService.CreaCompanyProfile(infoSession.accountId, comProfile);
            // reset session
            var newSession = new InfoViewModel()
            {
                accountId = infoSession.accountId,
                AccountType = infoSession.AccountType,
                FullName = infoSession.FullName,
                IscreateProfile = 1
            };
            HttpContext.Session.Remove("Usersession");
            HttpContext.Session.SetString("Usersession", JsonConvert.SerializeObject(newSession));
            return View();
        }
        [HttpGet("/UpdateCompanyProfile")]
        public async Task<IActionResult> UpdateCompanyProfile()
        {
            if (HttpContext.Session.GetString("Usersession") == null)
                return RedirectToAction("SignIn", "Home");

            InfoViewModel infoSession = new InfoViewModel();
            infoSession = JsonConvert.DeserializeObject<InfoViewModel>(HttpContext.Session.GetString("Usersession"));
            var modelProfile = await _companyService.GetCompanyProfile(infoSession.accountId);
            return View(modelProfile);
        }
        [HttpPost("/UpdateCompanyProfile")]
        public async Task<IActionResult> UpdateCompanyProfile(CompanyProfile comProfile)
        {
            if (HttpContext.Session.GetString("Usersession") == null)
                return RedirectToAction("SignIn");

            InfoViewModel infoSession = new InfoViewModel();
            infoSession = JsonConvert.DeserializeObject<InfoViewModel>(HttpContext.Session.GetString("Usersession"));
            await _companyService.CreaCompanyProfile(infoSession.accountId, comProfile);
            return RedirectToAction("UpdateCompanyProfile");
        }
        [HttpGet("/CreateJob")]
        public IActionResult CreateJob()
        {
            return View(new JobViewModel());
        }
        [HttpPost("/CreateJob")]
        public async Task<IActionResult> CreateJob(JobViewModel jobVM)
        {
            if (HttpContext.Session.GetString("Usersession") == null)
                return RedirectToAction("SignIn");

            InfoViewModel infoSession = new InfoViewModel();
            infoSession = JsonConvert.DeserializeObject<InfoViewModel>(HttpContext.Session.GetString("Usersession"));
            await _companyService.CreateJobAsync(infoSession.accountId, jobVM);

            return View();
        }
        [HttpGet("/UpdateJob")]
        public async Task<IActionResult> UpdateJob(Guid jobId)
        {
            if (HttpContext.Session.GetString("Usersession") == null)
                return RedirectToAction("SignIn");

            InfoViewModel infoSession = new InfoViewModel();
            infoSession = JsonConvert.DeserializeObject<InfoViewModel>(HttpContext.Session.GetString("Usersession"));
            var jobModel = await _companyService.GetJob(infoSession.accountId, jobId);
            return View(jobModel);
        }
        [HttpPost("/UpdateJob")]
        public async Task<IActionResult> UpdateJob(JobViewModel jobVM)
        {
            if (HttpContext.Session.GetString("Usersession") == null)
                return RedirectToAction("SignIn");

            InfoViewModel infoSession = new InfoViewModel();
            infoSession = JsonConvert.DeserializeObject<InfoViewModel>(HttpContext.Session.GetString("Usersession"));
            await _companyService.UpdateJob(infoSession.accountId, jobVM);
            return View(new JobViewModel());
        }
        public async Task<IActionResult> GetListJob()
        {
            if (HttpContext.Session.GetString("Usersession") == null)
                return RedirectToAction("SignIn");

            InfoViewModel infoSession = new InfoViewModel();
            infoSession = JsonConvert.DeserializeObject<InfoViewModel>(HttpContext.Session.GetString("Usersession"));
            var listJob = await _companyService.GetAllJobPerCompany(infoSession.accountId);
            return View(listJob);
        }
        public async Task<IActionResult> AppliedCV()
        {
            if (HttpContext.Session.GetString("Usersession") == null)
                return RedirectToAction("SignIn");

            InfoViewModel infoSession = new InfoViewModel();
            infoSession = JsonConvert.DeserializeObject<InfoViewModel>(HttpContext.Session.GetString("Usersession"));
            var model = await _companyService.GetListCvPerCompany(infoSession.accountId);
            return View(model);
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

CV-project/Views/Shared/_Layout.cshtml
@using Newtonsoft.Json;
@using Microsoft.AspNetCore.Http;
@using CV_project.Models;
@using Microsoft.AspNetCore.Mvc;
@inject IHttpContextAccessor Accessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WEEN</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="/css/layout-style.css" />


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container">
                <!--<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WEEN</a>-->
                <img id="weenlogo" src="/media/WEEN LOGO.svg" width="100" height="60" />
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="mynav_navbar">
                    @{ InfoViewModel infoSession = new InfoViewModel();
                        if (Accessor.HttpContext.Session.GetString("Usersession") != null)
                            infoSession = JsonConvert.DeserializeObject<InfoViewModel>(Accessor.HttpContext.Session.GetString("Usersession"));

                        if (infoSession.AccountType == 2)
                        {
                            //<a href="@Url.Action("CreateJob", "Company")">CREATE JOB</a>
                            <a href="@Url.Action("ViewCV", "Company")">PROFILE MATCHING</a>
                            //<a href="@Url.Action("AppliedCV", "Company")">APPLIED CV</a>
                        }
                        else if (infoSession.AccountType == 1)
                        {
                            //<a href="@Url.Action("CreateCV", "Home")">CREATE CV</a>
                            <a href="@Url.Action("ViewCompany", "Home")">PROFILE MATCHING</a>
                        }
                        else if (infoSession.AccountType == 3)
                        {<a href="@Url.Action("RegisterForCompany", "Admin")">CREATE ACCOUNT FOR COMPANY</a>
                        }
                        @if (infoSession.AccountType < 3)
                        {
                            <a href="@Url.Action("Headhunt", "Home")">HEADHUNT</a>
                            <a href="@Url.Action("viewevent", "Home")">EVENT</a>
                        }
                    }

                    <div class="mynav_dropdown">
                        <img id="avt" src="~/media/ava6.png" />
                        <div class="mynav_dropdown-content">
                            @{
                                if (Accessor.HttpContext.Session.GetString("Usersession") != null)
                                {
                                    InfoViewModel infoSS = new InfoViewModel();
                                    infoSS = JsonConvert.DeserializeObject<InfoViewModel>(Accessor.HttpContext.Session.GetString("Usersession"));
                                    @if (infoSession.AccountType < 3)
                                    {
                                        @if (infoSS.IscreateProfile == 0)
                                        {
                                            if (infoSS.AccountType == 1)
                                            {
                                                <a href="@Url.Action("CreateProfile", "Home")">Create Profile</a>
                                            }
                                            else
                                            {
                                                <a href="@Url.Action("CreateCompanyProfile", "Company")">Create Profile</a>
                                            }
                                        }
                                        else
                                        {
                                            if (infoSS.AccountType == 1)
                                            {
                                                <a href="@Url.Action("UpdateProfile", "Home")">View Profile</a>
                                            }
                                            else
                                            {
                                                <a href="@Url.Action("UpdateCompanyProfile", "Company")">View Profile</a>
                                            }
                                        }
                                    }
                                    @if (infoSS.AccountType == 2)
                                    {
                                        <a href="@Url.Action("GetListJob", "Company")">View Job</a>
                                        <a href="@Url.Action("CreateJob", "Company")">Create job</a>
                                        <a href="@Url.Action("AppliedCV", "Company")">Applied CV</a>
                                    }
                                    else if (infoSS.AccountType == 1)
                                    {
                                        <a href="@Url.Action("CreateCV", "Home")">Create CV</a>
                                        <a href="@Url.Action("UpdateCV", "Home")">View CV</a>
                                    }
                                    <a href="@Url.Action("Logout", "Home")">Log out</a>
                                }
                                else
                                {
                                    <a href="@Url.Action("CreateProfile", "Home")">Create Profile</a>
                                    <a href="@Url.Action("UpdateCV", "Home")">View CV</a>
                                    <a href="@Url.Action("SignIn", "Home")">Sign In</a>
                                }
                            }
                        </div>
                    </div>
                    <div>
                        @if (Accessor.HttpContext.Session.GetString("Usersession") != null)
                        {
                            InfoViewModel infoSS = new InfoViewModel();
                            infoSS = JsonConvert.DeserializeObject<InfoViewModel>(Accessor.HttpContext.Session.GetString("Usersession"));
                            <p>@infoSS.FullName</p>
                        }
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


</body>
</html>